### ISSUE TITLE
Uploading to SFTP using public ssh key from PAGEANT ENHANCEMENT

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#241]
Storage of passwords from keys not safely, using public ssh key from PAGEANT would help to increase safety and to make more transparent the authorization mechanism

p.s. How can I put label "ENHANCEMENT"?

**Comment by flarn2006** [comment]
I'd like to see this too. It would provide a good alternative to storing a password, which I'd rather not do (see #482.)

**Comment by Jaex** [comment]
I don't know how to make it.

**Comment by Zachu** [comment]
I also would like to see pageant support in ShareX, +1.

Integrating with pageant doesn't seem to be that well documented, or atleast I didn't find lots of information about it. I did find couple of pointers though.

Here's pageant support done with python: https://github.com/paramiko/paramiko/blob/master/paramiko/win_pageant.py

And here's an java class doing it https://github.com/ymnk/jsch-agent-proxy/blob/master/examples/src/main/java/com/jcraft/jsch/agentproxy/examples/UsingPageant.java https://github.com/ymnk/jsch-agent-proxy/blob/master/jsch-agent-proxy-pageant/src/main/java/com/jcraft/jsch/agentproxy/connector/PageantConnector.java

Also here's https://groups.google.com/forum/#!topic/comp.security.ssh/hZImYBowsCc someone asking the same thing and he's directed to look the C implementation of putty, here https://github.com/Yasushi/putty/blob/master/windows/winpgntc.c#L155

Hope this helps at all

**Comment by DoctorMcKay** [comment]
+1, would really like to see this

**Comment by arleslie** [comment]
You can still use SSH keys without pageant. 

Under SFTP in the FTP uploads, it allows you to set a keypath.

Just convert your pageant key to openssh and set the keypath to the file.

**Comment by DoctorMcKay** [comment]
I'd rather not have to a) enter a passphrase every time, or b) keep an unencrypted key on my disk.

**Comment by zingmars** [comment]
+1 would be nice

**Comment by Jaex** [comment]
I don't even have SFTP account while implementing SFTP therefore couldn't test anything. So it will be impossible for me to add such things. So this never gonna be implemented.

**Comment by QuAzI** [comment]
@Jaex 
SFTP account is any SSH-account which can upload file by SFTP or SCP.
You can use docker to play with SFTP/SCP , but currently Windows 10+ also has OpenSSH in app store.

Example of `docker-compose.yml` for test environment
```yaml
services:
    ssh-server:
      image: lscr.io/linuxserver/openssh-server:latest
      container_name: openssh-server
      hostname: openssh-server #optional
      environment:
        #- PUID=1000
        #- PGID=1000
        #- TZ=Etc/UTC
        #- PUBLIC_KEY=yourpublickey #optional
        #- PUBLIC_KEY_FILE=/path/to/file #optional
        #- PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
        - PUBLIC_KEY_URL=https://github.com/Jaex.keys #optional
        - SUDO_ACCESS=false #optional
        - PASSWORD_ACCESS=true #optional
        - USER_PASSWORD=pass #optional
        #- USER_PASSWORD_FILE=/path/to/file #optional
        - USER_NAME=user #optional
        - LOG_STDOUT= #optional
      volumes:
        - ./files:/files
      ports:
        - 2222:2222
      restart: unless-stopped
```

Currently, I don't even have a private SSH key on disk as all of them loads into Agent from KeePassXC
